//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registraton
    {
        public int Regid { get; set; }
        public Nullable<int> Cid { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<int> stdid { get; set; }
        public Nullable<int> did { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual department department { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
